version: '3'
services:
  discovery:
    image: smartlab/eureka-microservice
    build: ./eureka-service
    networks:
      - "discovery"
    ports:
      - "8761:8761"
  user:
    image: smartlab/user-microservice
    build: ./user-service
    networks:
      - "discovery"
    ports:
      - "8733:8733"
    depends_on:
      - discovery
  edge:
    image: smartlab/edge-microservice
    build: ./edge-service
    networks:
      - "discovery"
    ports:
      - "8732:8732"
    depends_on:
      - discovery
  consensus:
    image: smartlab/consensus-microservice
    build: ./consensus-service
    networks:
      - "discovery"
    ports:
      - "8742:8742"
    depends_on:
      - discovery

  coordinator:
    image: smartlab/coordinator-microservice
    build: ./coordinator-service
    networks:
      - "discovery"
    ports:
      - "5153:5153"
    depends_on:
      - discovery
#      - db

  prediction:
    image: smartlab/prediction-microservice
    build: ./prediction-service
    networks:
      - "discovery"
    ports:
      - "8752:8752"
    depends_on:
      - discovery

  sim:
    image: smartlab/sim
    build: ./front
    ports:
      - "4200:4200"
#  db:
#    image: mysql:5.7
#    volumes:
#      - /var/lib/mysql
#    restart: always
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: db
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
#    networks:
#      - "discovery"
#    ports:
#      - "33061:3306"
networks:
  discovery: